### ISSUE TITLE
Package overview eat-packages

### ISSUE THREAD

**Issue by nickhaf** [iqb-research/IQB-Methods#6]
Create an own chapter for the eat-packages, similar to here: 
http://iqbstaff.pbworks.com/w/page/29457501/ZK%20Datenanalyse

Create a markdown-table and copy the information into a new chapter on the webside.

**Comment by grewered** [comment]
@nickhaf is it possible with the new structure to have a page with links in it (like "material for learning R" atm) AND have it open up to more pages on the side?
otherwise I would try to just copy the page like in pbworks with all the cran and github links, etc.

**Comment by nickhaf** [comment]
Wouldn't that just be chapters on the page? Or did I understand something wrong?

**Comment by nickhaf** [comment]
Ah, so you would like an own chapter R Tutorials, which also shows underlying chapters? That can be achieved like this:

```
sidebar: 
    style: "docked"
    search: true
    contents:
      - href: r_tutorials.qmd
        contents:
          - docs/R/Tutorial_1.qmd
          - docs/R/Tutorial_2.qmd
```
This will have a main "R Tutorials" page, which also has the nested pages Tutorial 1 and Tutorial 2.
